-- MySQL Script generated by MySQL Workbench
-- sex 27 out 2017 19:26:06 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema final_php1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema final_php1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `final_php1` DEFAULT CHARACTER SET utf8 ;
USE `final_php1` ;

-- -----------------------------------------------------
-- Table `final_php1`.`proprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final_php1`.`proprietario` (
  `idproprietario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `nascimento` DATE NULL,
  `endereco` VARCHAR(245) NULL,
  `remuneracao` DECIMAL NULL,
  PRIMARY KEY (`idproprietario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_php1`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final_php1`.`marca` (
  `idmarca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`idmarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_php1`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `final_php1`.`veiculo` (
  `idveiculo` INT NOT NULL AUTO_INCREMENT,
  `proprietario_idproprietario` INT NOT NULL,
  `marca_idmarca` INT NOT NULL,
  `cor` VARCHAR(45) NULL,
  `fabricacao` DATE NULL,
  `tipo` CHAR NULL COMMENT 'c para Carro\nm para Moto\nn Navio\na - Avião\ng Guerra',
  `valor` DECIMAL NULL,
  `chassi` VARCHAR(45) NULL,
  PRIMARY KEY (`idveiculo`),
  INDEX `fk_veiculo_proprietario_idx` (`proprietario_idproprietario` ASC),
  INDEX `fk_veiculo_marca1_idx` (`marca_idmarca` ASC),
  CONSTRAINT `fk_veiculo_proprietario`
    FOREIGN KEY (`proprietario_idproprietario`)
    REFERENCES `final_php1`.`proprietario` (`idproprietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_marca1`
    FOREIGN KEY (`marca_idmarca`)
    REFERENCES `final_php1`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
