-- MySQL Script generated by MySQL Workbench
-- seg 17 set 2018 19:26:10 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema compras
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema compras
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compras` ;
USE `compras` ;

-- -----------------------------------------------------
-- Table `compras`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compras`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compras`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compras`.`Produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `codigo_barrras` VARCHAR(45) NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compras`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compras`.`Cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compras`.`ItemVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compras`.`ItemVenda` (
  `iditem_venda` INT NOT NULL,
  `preco` DECIMAL NULL,
  `produto_id_produto` INT NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`iditem_venda`),
  INDEX `fk_item_venda_Produto_idx` (`produto_id_produto` ASC) VISIBLE,
  INDEX `fk_item_venda_Cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_item_venda_Produto`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `compras`.`Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_venda_Cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `compras`.`Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
